// export enum COUNTIES {
//   'All',
//   'Alachua',
//   'Baker',
//   'Bay',
//   'Bradford',
//   'Brevard',
//   'Broward',
//   'Calhoun',
//   'Charlotte',
//   'Clay',
//   'Columbia',
//   'DeSoto',
//   'Duval',
//   'Escambia',
//   'Flagler',
//   'Franklin',
//   'Gadsden',
//   'Citrus',
//   'Gilchrist',
//   'Collier',
//   'Glades',
//   'Gulf',
//   'Dixie',
//   'Hamilton',
//   'Hardee',
//   'Hendry',
//   'Hernando',
//   'Highlands',
//   'Hillsborough',
//   'Holmes',
//   'Indian River',
//   'Jackson',
//   'Jefferson',
//   'Lafayette',
//   'Lake',
//   'Lee',
//   'Leon',
//   'Levy',
//   'Liberty',
//   'Madison',
//   'Manatee',
//   'Marion',
//   'Martin',
//   'Miami-Dade',
//   'Nassau',
//   'Okaloosa',
//   'Okeechobee',
//   'Orange',
//   'Osceola',
//   'Palm Beach',
//   'Pasco',
//   'Pinellas',
//   'Polk',
//   'Putnam',
//   'St. Johns',
//   'St. Lucie',
//   'Santa Rosa',
//   'Sarasota',
//   'Seminole',
//   'Sumter',
//   'Suwannee',
//   'Taylor',
//   'Union',
//   'Volusia',
//   'Wakulla',
//   'Walton',
//   'Washington',
//   'Unknown'
// }


export enum COUNTIES {
  'Miami-Dade' = 1,
  'Duval' = 2,
  'Hillsborough' = 3,
  'Pinellas' = 4,
  'Polk' = 5,
  'Palm Beach' = 6,
  'Orange' = 7,
  'Volusia' = 8,
  'Escambia' = 9,
  'Broward' = 10,
  'Alachua' = 11,
  'Lake' = 12,
  'Leon' = 13,
  'Marion' = 14,
  'Manatee' = 15,
  'Sarasota' = 16,
  'Seminole' = 17,
  'Lee' = 18,
  'Brevard' = 19,
  'St Johns' = 20,
  'Gadsden' = 21,
  'Putnam' = 22,
  'Bay' = 23,
  'St Lucie' = 24,
  'Jackson' = 25,
  'Osceola' = 26,
  'Highlands' = 27,
  'Pasco' = 28,
  'Columbia' = 29,
  'Indian River' = 32,
  'Santa Rosa' = 33,
  'DeSoto' = 34,
  'Madison' = 35,
  'Walton' = 36,
  'Taylor' = 37,
  'Monroe' = 38,
  'Levy' = 39,
  'Hernando' = 40,
  'Nassau' = 41,
  'Martin' = 42,
  'Okaloosa' = 43,
  'Sumter' = 44,
  'Bradford' = 45,
  'Jefferson' = 46,
  'Citrus' = 47,
  'Clay' = 48,
  'Hendry' = 49,
  'Washington' = 50,
  'Holmes' = 51,
  'Baker' = 52,
  'Charlotte' = 53,
  'Dixie' = 54,
  'Gilchrist' = 55,
  'Hamilton' = 56,
  'Okeechobee' = 57,
  'Calhoun' = 58,
  'Franklin' = 59,
  'Glades' = 60,
  'Lafayette' = 62,
  'Union' = 63,
  'Collier' = 64,
  'Wakulla' = 65,
  'Gulf' = 66,
  'Liberty' = 67,
  'Unknown' = 68
}
