export enum FDOT_AGENCIES {
  'Alachua Co SO',
  'Alachua PD',
  'Altamonte Springs PD',
  'Altha PD',
  'Apalachicola PD',
  'Apopka PD',
  'Arcadia PD',
  'Astatula PD',
  'Atlantic Beach PD',
  'Atlantis PD',
  'Auburndale PD',
  'Aventura PD',
  'Avon Park PD',
  'Baker Co SO',
  'Bal Harbour PD',
  'Bartow PD',
  'Bay Co SO',
  'Bay District Schools PD',
  'Bay Harbor Islands PD',
  'Beaches Intl Airport PD',
  'Belle Isle PD',
  'Belleair PD',
  'Belleview PD',
  'Biscayne Park PD',
  'Blountstown PD',
  'Boca Raton PD',
  'Bonifay PD',
  'Bowling Green PD',
  'Boynton Beach PD',
  'Bradenton Beach PD',
  'Bradenton PD',
  'Bradford Co SO',
  'Brevard Co SO',
  'Brooksville PD',
  'Broward Co SO',
  'Bunnell PD',
  'Bushnell PD',
  'Calhoun Co SO',
  'Cape Coral PD',
  'Carrabelle PD',
  'Casselberry PD',
  'Cedar Key PD',
  'Center Hill PD',
  'Charlotte Co SO',
  'Chattahoochee PD',
  'Chiefland PD',
  'Chipley PD',
  'Citrus Co SO',
  'Clay Co SO',
  'Clearwater PD',
  'Clermont PD',
  'Clewiston PD',
  'Cocoa Beach PD',
  'Cocoa PD',
  'Coconut Creek PD',
  'Collier Co SO',
  'Columbia Co SO',
  'Coral Gables PD',
  'Coral Springs PD',
  'Cottondale PD',
  'Crescent City PD',
  'Crestview PD',
  'Cross City PD',
  'Crystal River PD',
  'Cutler Bay PD',
  'Dade City PD',
  'Davenport PD',
  'Davie PD',
  'Daytona Beach Airport PD',
  'Daytona Beach PD',
  'Daytona Beach Shores PD',
  'DeFuniak Springs PD',
  'Deland PD',
  'Delray Beach PD',
  'DeSoto Co SO',
  'Dixie Co SO',
  'Doral PD',
  'Dunnellon PD',
  'Duval Co Schools PD',
  'Eatonville PD',
  'Edgewater PD',
  'Edgewood PD',
  'El Portal PD',
  'Escambia Co SO',
  'Eustis PD',
  'FAMU PD',
  'FAU (Broward Campus) PD',
  'FAU PD',
  'FDOT',
  'Fellsmere PD',
  'Fernandina Beach PD',
  'FGCU PD',
  'FHP',
  'FHP Troop A',
  'FHP Troop B',
  'FHP Troop C',
  'FHP Troop D',
  'FHP Troop E',
  'FHP Troop F',
  'FHP Troop G',
  'FHP Troop H',
  'FHP Troop I',
  'FHP Troop J',
  'FHP Troop K',
  'FHP Troop L',
  'FHP Troop Q',
  'Fish & Wildlife Conservation',
  'FIU PD',
  'Flagler Beach PD',
  'Flagler Co SO',
  'Florida City PD',
  'Florida East Coast Railway PD',
  'Florida Polytechnic University PD',
  'Florida Southwestern State College PD',
  'Fort Lauderdale PD',
  'Fort Myers PD',
  'Fort Pierce PD',
  'Fort Walton Beach PD',
  'Franklin Co SO',
  'Fruitland Park PD',
  'FSDB PD',
  'FSU (Panama City) PD',
  'FSU PD',
  'Gadsden Co SO',
  'Gainesville PD',
  'Gilchrist Co SO',
  'Glades Co SO',
  'Golden Beach PD',
  'Graceville PD',
  'Green Cove Springs PD',
  'Greenacres PD',
  'Greensboro PD',
  'Gretna PD',
  'Groveland PD',
  'Gulf Breeze PD',
  'Gulf Co SO',
  'Gulf Stream PD',
  'Gulfport PD',
  'Haines City PD',
  'Hallandale Beach PD',
  'Hamilton Co SO',
  'Hampton PD'
  'Hardee Co SO',
  'Havana PD',
  'Hendry Co SO',
  'Hernando Co SO',
  'Hialeah Gardens PD',
  'Hialeah PD',
  'High Springs PD',
  'Highland Beach PD',
  'Highlands Co SO',
  'Hillsboro Beach PD',
  'Hillsborough Co SO',
  'Holly Hill PD',
  'Hollywood PD',
  'Holmes Beach PD',
  'Holmes Co SO',
  'Homestead PD',
  'Howey in the Hills PD',
  'Indialantic PD',
  'Indian Creek Village PD',
  'Indian Harbour Beach PD',
  'Indian River Co SO',
  'Indian River Shores PD',
  'Indian Shores PD',
  'Inglis PD',
  'Interlachen PD',
  'Jackson Co SO',
  'Jacksonville Aviation Authority PD',
  'Jacksonville Beach PD',
  'Jacksonville SO',
  'Jasper PD',
  'Jefferson Co SO',
  'Jennings PD',
  'Juno Beach PD',
  'Jupiter Inlet Colony PD',
  'Jupiter Island PD',
  'Jupiter PD',
  'Kennedy Space Center PD',
  'Kenneth City PD',
  'Key Biscayne PD',
  'Key Colony Beach PD',
  'Key West PD',
  'Kissimmee PD',
  'Lady Lake PD',
  'Lafayette Co SO',
  'Lake Alfred PD',
  'Lake City PD',
  'Lake Clarke Shores PD',
  'Lake Co SO',
  'Lake Hamilton PD',
  'Lake Helen PD',
  'Lake Mary PD',
  'Lake Placid PD',
  'Lake Wales PD',
  'Lakeland PD',
  'Lantana PD',
  'Largo PD',
  'Lauderhill PD',
  'Lawtey PD',
  'Lee Co Port Auth PD',
  'Lee Co SO',
  'Lee Co Toll Auth',
  'Leesburg PD',
  'Leon Co SO',
  'Levy Co SO',
  'Liberty Co SO',
  'Lighthouse Point PD',
  'Live Oak PD',
  'Longboat Key PD',
  'Longwood PD',
  'Lynn Haven PD',
  'Madison Co SO',
  'Madison PD',
  'Maitland PD',
  'Manalapan PD',
  'Manatee Co SO',
  'Marco Island PD',
  'Margate PD',
  'Marianna PD',
  'Marion Co SO',
  'Martin Co SO',
  'Mascotte PD',
  'Medley PD',
  'Melbourne Airport PD',
  'Melbourne Beach PD',
  'Melbourne PD',
  'Melbourne Village PD',
  'Mexico Beach PD',
  'Miami Beach PD',
  'Miami Gardens PD',
  'Miami PD',
  'Miami Shores PD',
  'Miami Springs PD',
  'Miami-Dade Co Schools PD',
  'Miami-Dade Expwy Auth',
  'Miami-Dade PD',
  'Miccosukee Indian Res PD',
  'Midway PD',
  'Milton PD',
  'Miramar PD',
  'Monroe Co SO',
  'Monticello PD',
  'Mount Dora PD',
  'Naples PD',
  'Nassau Co SO',
  'Neptune Beach PD',
  'New College of Florida PD',
  'New Port Richey PD',
  'New Smyrna Beach PD',
  'Niceville PD',
  'North Bay Village PD',
  'North Miami Beach PD',
  'North Miami PD',
  'North Palm Beach PD',
  'North Port PD',
  'Oak Hill PD',
  'Oakland PD',
  'Ocala PD',
  'Ocean Ridge PD',
  'Ocoee PD',
  'Okaloosa Co Airport PD',
  'Okaloosa Co SO',
  'Okeechobee Co SO',
  'Okeechobee PD',
  'Opa Locka PD',
  'Orange City PD',
  'Orange Co SO',
  'Orange Park PD',
  'Orchid PD',
  'Orlando City Code Enforcement',
  'Orlando Expwy Auth',
  'Orlando PD',
  'Ormond Beach PD',
  'Osceola Co SO',
  'Oviedo PD',
  'Palatka PD',
  'Palm Bay PD',
  'Palm Beach Co Schools PD',
  'Palm Beach Co SO',
  'Palm Beach Gardens PD',
  'Palm Beach PD',
  'Palm Beach Shores PD',
  'Palm Springs PD',
  'Palmetto Bay PD',
  'Palmetto PD',
  'Panama City Beach PD',
  'Panama City PD',
  'Parker PD',
  'Pasco Co SO',
  'Pembroke Pines PD',
  'Pensacola PD',
  'Perry PD',
  'Pinecrest PD',
  'Pinellas Co SO',
  'Pinellas County Schools PD',
  'Pinellas Park PD',
  'Plant City PD',
  'Plantation PD',
  'Polk Co SO',
  'Ponce Inlet PD',
  'Port Canaveral PD',
  'Port Orange PD',
  'Port Richey PD',
  'Port St Joe PD',
  'Port St Lucie PD',
  'PSC (Milton Campus) PD',
  'PSC PD',
  'Punta Gorda PD',
  'Putnam Co Schools PD',
  'Putnam Co SO',
  'Quincy PD',
  'Riviera Beach PD',
  'Rockledge PD',
  'Sanford Intl Airport PD',
  'Sanford PD',
  'Sanibel PD',
  'Santa Rosa Co SO',
  'Sarasota Co SO',
  'Sarasota PD',
  'Sarasota-Bradenton Airport PD',
  'Satellite Beach PD',
  'Sea Ranch Lakes PD',
  'Sebastian PD',
  'Sebring PD',
  'Seminole Co SO',
  'Seminole Indian Res PD',
  'Sewall\'s Point PD',
  'SFC PD',
  'Shalimar PD',
  'Sneads PD',
  'South Daytona PD',
  'South Miami PD',
  'South Palm Beach PD',
  'Springfield PD',
  'St Augustine Beach PD',
  'St Augustine PD',
  'St Cloud PD',
  'St Johns Co SO',
  'St Lucie Co SO',
  'St Pete Beach PD',
  'St Pete-Clearwater Airport PD',
  'St Petersburg PD',
  'Starke PD',
  'State Capitol PD',
  'Stuart PD',
  'Sumter Co SO',
  'Sunny Isles Beach PD',
  'Sunrise PD',
  'Surfside PD',
  'Suwannee Co SO',
  'Sweetwater PD',
  'Tallahassee PD',
  'Tampa Intl Airport PD',
  'Tampa PD',
  'Tarpon Springs PD',
  'Tavares PD',
  'Taylor Co SO',
  'TCC PD',
  'Temple Terrace PD',
  'Tequesta PD',
  'Titusville PD',
  'Treasure Island PD',
  'Trenton PD',
  'UCF PD',
  'UF PD',
  'Umatilla PD',
  'UNF PD',
  'Union Co SO',
  'USF (Pinellas Campus) PD',
  'USF PD',
  'UWF PD',
  'Valparaiso PD',
  'Venice PD',
  'Vero Beach PD',
  'Virginia Gardens PD',
  'Volusia Co Beach Patrol',
  'Volusia Co SO',
  'Wakulla Co SO',
  'Waldo PD',
  'Walton Co SO',
  'Washington Co SO',
  'Wauchula PD',
  'Webster PD',
  'West Melbourne PD',
  'West Miami PD',
  'West Palm Beach PD',
  'White Springs PD',
  'Wildwood PD',
  'Williston PD',
  'Wilton Manors PD',
  'Windermere PD',
  'Winter Garden PD',
  'Winter Haven PD',
  'Winter Park PD',
  'Winter Springs PD',
  'Zephyrhills PD',
  'Zolfo Springs PD',
  'Baldwin PD',
  'Belle Glade PD',
  'Belleair Beach PD',
  'Briny Breezes PD',
  'Brooker PD',
  'Cedar Grove PD',
  'Coleman PD',
  'Cooper City PD',
  'Dundee PD',
  'Eagle Lake PD',
  'Eastpoint PD',
  'Fort Meade PD',
  'Frostproof PD',
  'Greenville PD',
  'Hawthorne PD',
  'Hilliard PD',
  'Hypoluxo PD',
  'Inverness PD',
  'Lake Park PD',
  'Lake Worth PD',
  'Land O Lakes PD',
  'Lauderdale by the Sea PD',
  'Lee PD',
  'Madeira Beach PD',
  'Mangonia Park PD',
  'Minneola PD',
  'Mulberry PD',
  'North Lauderdale PD',
  'Oakland Park PD',
  'Pahokee PD',
  'Parkland PD',
  'Paxton PD',
  'Polk City PD',
  'Pomona Park PD',
  'Pompano Beach PD',
  'Redington Beach PD',
  'Royal Palm Beach PD',
  'South Bay PD',
  'Welaka PD'
}
