export enum FDOT_AGENCIES {
  'Bay County MPO',
  'Broward MPO',
  'Capital Region TPA',
  'Charlotte County-Punta Gorda MPO',
  'Collier County MPO',
  'Florida-Alabama TPO',
  'Gainesville MTPO',
  'Hernando County MPO',
  'Hillsborough County MPO',
  'Indian River County MPO',
  'Lake-Sumter MPO',
  'Lee County MPO',
  'Martin County MPO',
  'Metroplan Orlando',
  'Miami-Dade Urbanized Area MPO',
  'North Florida TPO',
  'Ocala-Marion County TPO',
  'Okaloosa-Walton TPO',
  'Palm Beach County MPO',
  'Pasco County MPO',
  'Pinellas County MPO',
  'Polk TPO',
  'Sarasota-Manatee MPO',
  'Space Coast TPO',
  'St Lucie TPO',
  'Volusia County MPO'
}
