namespace S4Sales
{
    public enum Counties
    {
        Alachua,
        Baker,
        Bay,
        Bradford,
        Brevard,
        Broward,
        Calhoun,
        Charlotte,
        Clay,
        Columbia,
        DeSoto,
        Duval,
        Escambia,
        Flagler,
        Franklin,
        Gadsden,
        Citrus,
        Gilchrist,
        Collier,
        Glades,
        Gulf,
        Dixie,
        Hamilton,
        Hardee,
        Hendry,
        Hernando,
        Highlands,
        Hillsborough,
        Holmes,
        Indian River,
        Jackson,
        Jefferson,,
        Lafayette,
        Lake,
        Lee,
        Leon,
        Levy,
        Liberty,
        Madison,
        Manatee,
        Marion,
        Martin,
        Miami-Dade,
        Nassau,
        Okaloosa,
        Okeechobee,
        Orange,
        Osceola,
        Palm Beach,
        Pasco,
        Pinellas,
        Polk,
        Putnam,
        St. Johns,
        St. Lucie,
        Santa Rosa,
        Sarasota,
        Seminole,
        Sumter,
        Suwannee,
        Taylor,
        Union,
        Volusia,
        Wakulla,
        Walton,
        Washington
    }
}